# -*- coding: utf-8 -*-
# MGEX_name      : MGEX site Long and short name comparison information
# Author         : Chang Chuntao
# Copyright(C)   : The GNSS Center, Wuhan University 
# Latest Version : 1.21
# Creation Date  : 2022.03.27 - Version 1.00
# Date           : 2022.09.16 - Version 1.21

"""
2022-03-27 : MGEX长短名索引表                 by Chang Chuntao -> Version : 1.00
2022-09-16 : MGEX_HK_cors长短名索引表         by Chang Chuntao -> Version : 1.21
"""

from fast.com.mgexSite import readMegxSiteInf
import os, sys

def replaceSiteStr(ftpInList, siteInList):
    """
    2022-09-16 :    替换站点字符串
                    by Chang Chuntao  -> Version : 1.21
    2023-01-14 :    支持大小长短自由
                    by Chang Chuntao  -> Version : 2.06
    2023-03-12 :    新增SITE_SHORT,支持时间序列产品下载
                    by Chang Chuntao  -> Version : 2.18
    """
    upperSite = ''
    if len(siteInList) == 4:
        lowSite = str(siteInList).lower()
        upperShortSite = lowSite.upper()
        for mgexSite in mgex:
            if mgexSite[0] == lowSite:
                upperSite = mgexSite[1]
    elif len(siteInList) == 9:
        lowSite = str(siteInList[0:4]).lower()
        upperSite = str(siteInList).upper()
        upperShortSite = lowSite.upper()
    else:
        lowSite = ''
        upperSite = ''
        upperShortSite = ''
    if '<SITE>' in ftpInList:
        ftpInList = str(ftpInList).replace('<SITE>', lowSite)
    if '<SITE_LONG>' in ftpInList:
        ftpInList = str(ftpInList).replace('<SITE_LONG>', upperSite)
    if '<SITE_SHORT>' in ftpInList:
        ftpInList = str(ftpInList).replace('<SITE_SHORT>', upperShortSite)
    return ftpInList

if getattr(sys, 'frozen', False):
    dirname = os.path.dirname(sys.executable)
else:
    dirname = os.path.dirname(os.path.abspath(__file__))
    dirname = os.path.join(dirname, '..')


# get mgex inf
igsFileCsv = os.path.join(dirname, 'win_bin', 'bin', 'IGSNetwork.csv')
if not os.path.isfile(igsFileCsv):
    igsFileCsv = os.path.join(dirname, 'bin', 'IGSNetwork.csv')
if not os.path.isfile(igsFileCsv):
    igsFileCsv = os.path.join(dirname, 'mac_bin', 'IGSNetwork.csv')
megxSiteList = readMegxSiteInf(igsFileCsv)

mgex = []
for mgexShort in megxSiteList:
    mgexLoog = megxSiteList[mgexShort]['LongName']
    mgex.append([mgexShort, mgexLoog])

supplementSite = [
        ['hksl', 'HKSL00HKG'],
        ['hkws', 'HKWS00HKG'],
        ['mas1', 'MAS100ESP'],
        ['lpal', 'LPAL00ESP'],
        ['ramo', 'RAMO00ISR'],
        ['drag', 'DRAG00ISR'],
        ['func', 'FUNC00PRT'],
        ['rabt', 'RABT00MAR'],
        ['nico', 'NICO00CYP'],
        ['meli', 'MELI00ESP'],
        ['sfer', 'SFER00ESP'],
        ['mers', 'MERS00TUR'],
        ['not1', 'NOT100ITA'],
        ['raeg', 'RAEG00PRT'],
        ['pdel', 'PDEL00PRT'],
        ['dyng', 'DYNG00GRC'],
        ['izmi', 'IZMI00TUR'],
        ['enao', 'ENAO00PRT'],
        ['flrs', 'FLRS00PRT'],
        ['ank2', 'ANK200TUR'],
        ['mad2', 'MAD200ESP'],
        ['madr', 'MADR00ESP'],
        ['vill', 'VILL00ESP'],
        ['cebr', 'CEBR00ESP'],
        ['yebe', 'YEBE00ESP'],
        ['krs1', 'KRS100TUR'],
        ['matg', 'MATG00ITA'],
        ['mat1', 'MAT100ITA'],
        ['mate', 'MATE00ITA'],
        ['tubi', 'TUBI00TUR'],
        ['ebre', 'EBRE00ESP'],
        ['ista', 'ISTA00TUR'],
        ['orid', 'ORID00MKD'],
        ['m0se', 'M0SE00ITA'],
        ['ajac', 'AJAC00FRA'],
        ['sofi', 'SOFI00BGR'],
        ['mars', 'MARS00FRA'],
        ['tlsg', 'TLSG00FRA'],
        ['tlse', 'TLSE00FRA'],
        ['grac', 'GRAC00FRA'],
        ['gras', 'GRAS00FRA'],
        ['zeck', 'ZECK00RUS'],
        ['geno', 'GENO00ITA'],
        ['bucu', 'BUCU00ROU'],
        ['medi', 'MEDI00ITA'],
        ['ieng', 'IENG00ITA'],
        ['pado', 'PADO00ITA'],
        ['lroc', 'LROC00FRA'],
        ['bzr2', 'BZR200ITA'],
        ['zim2', 'ZIM200CHE'],
        ['zimm', 'ZIMM00CHE'],
        ['mikl', 'MIKL00UKR'],
        ['graz', 'GRAZ00AUT'],
        ['penc', 'PENC00HUN'],
        ['brmg', 'BRMG00DEU'],
        ['obe4', 'OBE400DEU'],
        ['brst', 'BRST00FRA'],
        ['uzhl', 'UZHL00UKR'],
        ['ganp', 'GANP00SVK'],
        ['wtza', 'WTZA00DEU'],
        ['wtzr', 'WTZR00DEU'],
        ['wtzz', 'WTZZ00DEU'],
        ['wtzs', 'WTZS00DEU'],
        ['polv', 'POLV00UKR'],
        ['sulp', 'SULP00UKR'],
        ['gop6', 'GOP600CZE'],
        ['gope', 'GOPE00CZE'],
        ['redu', 'REDU00BEL'],
        ['khar', 'KHAR00UKR'],
        ['ffmj', 'FFMJ00DEU'],
        ['glsv', 'GLSV00UKR'],
        ['brux', 'BRUX00BEL'],
        ['hers', 'HERS00GBR'],
        ['hert', 'HERT00GBR'],
        ['tit2', 'TIT200DEU'],
        ['wroc', 'WROC00POL'],
        ['baut', 'BAUT00DEU'],
        ['leij', 'LEIJ00DEU'],
        ['licc', 'LICC00GBR'],
        ['dlf1', 'DLF100NLD'],
        ['joze', 'JOZE00POL'],
        ['joz2', 'JOZ200POL'],
        ['kos1', 'KOS100NLD'],
        ['bor1', 'BOR100POL'],
        ['ptbb', 'PTBB00DEU'],
        ['pots', 'POTS00DEU'],
        ['bogi', 'BOGI00POL'],
        ['wsrt', 'WSRT00NLD'],
        ['lama', 'LAMA00POL'],
        ['warn', 'WARN00DEU'],
        ['morp', 'MORP00GBR'],
        ['mdvj', 'MDVJ00RUS'],
        ['riga', 'RIGA00LVA'],
        ['ons1', 'ONS100SWE'],
        ['onsa', 'ONSA00SWE'],
        ['vis0', 'VIS000SWE'],
        ['spt0', 'SPT000SWE'],
        ['met3', 'MET300FIN'],
        ['mets', 'METS00FIN'],
        ['metg', 'METG00FIN'],
        ['svtl', 'SVTL00RUS'],
        ['mar6', 'MAR600SWE'],
        ['mar7', 'MAR700SWE'],
        ['qaq1', 'QAQ100GRL'],
        ['reyk', 'REYK00ISL'],
        ['hofn', 'HOFN00ISL'],
        ['sod3', 'SOD300FIN'],
        ['kiru', 'KIRU00SWE'],
        ['kir8', 'KIR800SWE'],
        ['kir0', 'KIR000SWE'],
        ['tro1', 'TRO100NOR'],
        ['scor', 'SCOR00GRL'],
        ['wuth', 'WUTH00NOR'],
        ['nya1', 'NYA100NOR'],
        ['nyal', 'NYAL00NOR'],
        ['nya2', 'NYA200NOR'],
        ['nabg', 'NABG00NOR'],
        ['acor', 'ACOR00ESP'] ,
        ['adar', 'ADAR00GBR'] ,
        ['adh1', 'ADH100ARE'] ,
        ['agrn', 'AGRN00ITA'] ,
        ['alac', 'ALAC00ESP'] ,
        ['alba', 'ALBA00ESP'] ,
        ['alme', 'ALME00ESP'] ,
        ['aqui', 'AQUI00ITA'] ,
        ['ara2', 'ARA200SVN'] ,
        ['argi', 'ARGI00FRO'] ,
        ['aris', 'ARIS00GBR'] ,
        ['arj6', 'ARJ600SWE'] ,
        ['asga', 'ASGA00CYP'] ,
        ['asir', 'ASIR00ITA'] ,
        ['aubg', 'AUBG00DEU'] ,
        ['auri', 'AURI00DEU'] ,
        ['aut0', 'AUT000USA'] ,
        ['aut1', 'AUT100GRC'] ,
        ['autn', 'AUTN00FRA'] ,
        ['axpv', 'AXPV00FRA'] ,
        ['azgb', 'AZGB00USA'] ,
        ['baca', 'BACA00ROU'] ,
        ['badh', 'BADH00DEU'] ,
        ['baia', 'BAIA00ROU'] ,
        ['bbys', 'BBYS00SVK'] ,
        ['bcln', 'BCLN00ESP'] ,
        ['bell', 'BELL00ESP'] ,
        ['bfo1', 'BFO100DEU'] ,
        ['bfst', 'BFST00GBR'] ,
        ['birg', 'BIRG00ITA'] ,
        ['bme1', 'BME100HUN'] ,
        ['boge', 'BOGE00POL'] ,
        ['bogo', 'BOGO00POL'] ,
        ['bolg', 'BOLG00ITA'] ,
        ['borj', 'BORJ00DEU'] ,
        ['borr', 'BORR00ESP'] ,
        ['bpdl', 'BPDL00POL'] ,
        ['bpeb', 'BPEB00CAN'] ,
        ['brdx', 'BRDX00WRD'] ,
        ['brmf', 'BRMF00FRA'] ,
        ['brts', 'BRTS00BLR'] ,
        ['bscn', 'BSCN00FRA'] ,
        ['bsvz', 'BSVZ00ITA'] ,
        ['budd', 'BUDD00DNK'] ,
        ['budp', 'BUDP00DNK'] ,
        ['bute', 'BUTE00HUN'] ,
        ['bydg', 'BYDG00POL'] ,
        ['cace', 'CACE00ESP'] ,
        ['cag1', 'CAG100ITA'] ,
        ['cako', 'CAKO00HRV'] ,
        ['cant', 'CANT00ESP'] ,
        ['carg', 'CARG00ESP'] ,
        ['casc', 'CASC00PRT'] ,
        ['case', 'CASE00ESP'] ,
        ['ceu1', 'CEU100ESP'] ,
        ['cfrm', 'CFRM00CZE'] ,
        ['chio', 'CHIO00GBR'] ,
        ['chiz', 'CHIZ00FRA'] ,
        ['cimo', 'CIMO00ITA'] ,
        ['clib', 'CLIB00CZE'] ,
        ['cmel', 'CMEL00ITA'] ,
        ['cniv', 'CNIV00UKR'] ,
        ['cnne', 'CNNE00FRA'] ,
        ['coba', 'COBA00ESP'] ,
        ['como', 'COMO00ITA'] ,
        ['cost', 'COST00ROU'] ,
        ['cpar', 'CPAR00CZE'] ,
        ['cpxf', 'CPXF00USA'] ,
        ['crak', 'CRAK00CZE'] ,
        ['creu', 'CREU00ESP'] ,
        ['ctab', 'CTAB00CZE'] ,
        ['ctwn', 'CTWN00ZAF'] ,
        ['cuga', 'CUGA00ITA'] ,
        ['dare', 'DARE00GBR'] ,
        ['daun', 'DAUN00DEU'] ,
        ['delf', 'DELF00NLD'] ,
        ['dent', 'DENT00BEL'] ,
        ['deva', 'DEVA00ROU'] ,
        ['dgor', 'DGOR00MNE'] ,
        ['diep', 'DIEP00DEU'] ,
        ['dill', 'DILL00DEU'] ,
        ['dnmu', 'DNMU00UKR'] ,
        ['dour', 'DOUR00BEL'] ,
        ['dub2', 'DUB200HRV'] ,
        ['duth', 'DUTH00GRC'] ,
        ['dvcn', 'DVCN00SVK'] ,
        ['efbg', 'EFBG00DEU'] ,
        ['eglt', 'EGLT00FRA'] ,
        ['eijs', 'EIJS00NLD'] ,
        ['ekar', 'EKAR00ITA'] ,
        ['elba', 'ELBA00ITA'] ,
        ['entz', 'ENTZ00FRA'] ,
        ['enza', 'ENZA00ITA'] ,
        ['erla', 'ERLA00DEU'] ,
        ['es13', 'ES1300DEU'] ,
        ['es14', 'ES1400DEU'] ,
        ['es17', 'ES1700DEU'] ,
        ['esco', 'ESCO00ESP'] ,
        ['esoc', 'ESOC00DEU'] ,
        ['eur2', 'EUR200CAN'] ,
        ['eusk', 'EUSK00DEU'] ,
        ['fins', 'FINS00FIN'] ,
        ['foyl', 'FOYL00GBR'] ,
        ['fra2', 'FRA200UKR'] ,
        ['frne', 'FRNE00ITA'] ,
        ['gaia', 'GAIA00PRT'] ,
        ['galh', 'GALH00ITA'] ,
        ['gari', 'GARI00ITA'] ,
        ['gdrs', 'GDRS00UKR'] ,
        ['gell', 'GELL00DEU'] ,
        ['gjml', 'GJML00SRB'] ,
        ['gldr', 'GLDR00CAN'] ,
        ['goet', 'GOET00DEU'] ,
        ['goml', 'GOML00BLR'] ,
        ['gor2', 'GOR200DEU'] ,
        ['gsr1', 'GSR100SVN'] ,
        ['guip', 'GUIP00FRA'] ,
        ['gvnl', 'GVNL00ITA'] ,
        ['gwwl', 'GWWL00POL'] ,
        ['has6', 'HAS600SWE'] ,
        ['hel2', 'HEL200DEU'] ,
        ['helg', 'HELG00DEU'] ,
        ['hett', 'HETT00FIN'] ,
        ['hobu', 'HOBU00DEU'] ,
        ['hofj', 'HOFJ00DEU'] ,
        ['hol2', 'HOL200DEU'] ,
        ['huel', 'HUEL00ESP'] ,
        ['ibiz', 'IBIZ00ESP'] ,
        ['iddr', 'IDDR00USA'] ,
        ['ifsc', 'IFSC00BRA'] ,
        ['igd1', 'IGD100GRC'] ,
        ['igeo', 'IGEO00MDA'] ,
        ['igm2', 'IGM200ITA'] ,
        ['igmi', 'IGMI00ITA'] ,
        ['igne', 'IGNE00ESP'] ,
        ['ignf', 'IGNF00FRA'] ,
        ['ijmu', 'IJMU00NLD'] ,
        ['ildx', 'ILDX00FRA'] ,
        ['invr', 'INVR00GBR'] ,
        ['irbe', 'IRBE00LVA'] ,
        ['irkt', 'IRKT00RUS'] ,
        ['isrn', 'ISRN00ITA'] ,
        ['izan', 'IZAN00ESP'] ,
        ['jate', 'JATE00ITA'] ,
        ['joe2', 'JOE200FIN'] ,
        ['joen', 'JOEN00FIN'] ,
        ['jon6', 'JON600SWE'] ,
        ['kad6', 'KAD600SWE'] ,
        ['karl', 'KARL00DEU'] ,
        ['kato', 'KATO00POL'] ,
        ['kda2', 'KDA200SVN'] ,
        ['kev2', 'KEV200FIN'] ,
        ['kilp', 'KILP00FIN'] ,
        ['kiv2', 'KIV200FIN'] ,
        ['klad', 'KLAD00SRB'] ,
        ['klnk', 'KLNK00BLR'] ,
        ['klop', 'KLOP00DEU'] ,
        ['knja', 'KNJA00SRB'] ,
        ['kra1', 'KRA100POL'] ,
        ['kraw', 'KRAW00POL'] ,
        ['krrs', 'KRRS00UKR'] ,
        ['ktvl', 'KTVL00UKR'] ,
        ['kunz', 'KUNZ00CZE'] ,
        ['kure', 'KURE00EST'] ,
        ['kuu2', 'KUU200FIN'] ,
        ['lago', 'LAGO00PRT'] ,
        ['lamp', 'LAMP00ITA'] ,
        ['larm', 'LARM00GRC'] ,
        ['lcra', 'LCRA00ITA'] ,
        ['ldb2', 'LDB200DEU'] ,
        ['lei3', 'LEI300DEU'] ,
        ['lek6', 'LEK600SWE'] ,
        ['leon', 'LEON00ESP'] ,
        ['leri', 'LERI00GBR'] ,
        ['lesk', 'LESK00SRB'] ,
        ['lida', 'LIDA00BLR'] ,
        ['lign', 'LIGN00ITA'] ,
        ['lil2', 'LIL200FRA'] ,
        ['linz', 'LINZ00AUT'] ,
        ['lliv', 'LLIV00ESP'] ,
        ['lodz', 'LODZ00POL'] ,
        ['lov6', 'LOV600SWE'] ,
        ['lyr1', 'LYR100NOR'] ,
        ['mah1', 'MAH100IRL'] ,
        ['mala', 'MALA00ESP'] ,
        ['mall', 'MALL00ESP'] ,
        ['man2', 'MAN200FRA'] ,
        ['mao0', 'MAO000USA'] ,
        ['marp', 'MARP00UKR'] ,
        ['mdeu', 'MDEU00ITA'] ,
        ['mik3', 'MIK300FIN'] ,
        ['mkrs', 'MKRS00UKR'] ,
        ['mlhd', 'MLHD00IRL'] ,
        ['mlvl', 'MLVL00FRA'] ,
        ['mmet', 'MMET00ITA'] ,
        ['mnkw', 'MNKW00BLR'] ,
        ['mnls', 'MNLS00USA'] ,
        ['mnsk', 'MNSK00BLR'] ,
        ['mogi', 'MOGI00BLR'] ,
        ['mop2', 'MOP200SVK'] ,
        ['mopi', 'MOPI00SVK'] ,
        ['mops', 'MOPS00ITA'] ,
        ['mox2', 'MOX200DEU'] ,
        ['mrib', 'MRIB00CAN'] ,
        ['msel', 'MSEL00ITA'] ,
        ['msgr', 'MSGR00BRA'] ,
        ['muk2', 'MUK200UKR'] ,
        ['myva', 'MYVA00ISL'] ,
        ['newl', 'NEWL00GBR'] ,
        ['noa1', 'NOA100GRC'] ,
        ['nor7', 'NOR700SWE'] ,
        ['novp', 'NOVP00BLR'] ,
        ['npaz', 'NPAZ00SRB'] ,
        ['nrmg', 'NRMG00NCL'] ,
        ['olk2', 'OLK200FIN'] ,
        ['onrj', 'ONRJ00BRA'] ,
        ['oriv', 'ORIV00FIN'] ,
        ['oros', 'OROS00HUN'] ,
        ['orte', 'ORTE00ITA'] ,
        ['osk6', 'OSK600SWE'] ,
        ['osl1', 'OSL100NOR'] ,
        ['osls', 'OSLS00NOR'] ,
        ['osna', 'OSNA00DEU'] ,
        ['ost6', 'OST600SWE'] ,
        ['oul2', 'OUL200FIN'] ,
        ['ove6', 'OVE600SWE'] ,
        ['palb', 'PALB00ITA'] ,
        ['pasa', 'PASA00ESP'] ,
        ['pat0', 'PAT000GRC'] ,
        ['pfa3', 'PFA300AUT'] ,
        ['pins', 'PINS00BLR'] ,
        ['plnd', 'PLND00SRB'] ,
        ['pmth', 'PMTH00GBR'] ,
        ['poli', 'POLI00BRA'] ,
        ['popi', 'POPI00ITA'] ,
        ['pore', 'PORE00HRV'] ,
        ['pous', 'POUS00CZE'] ,
        ['poze', 'POZE00HRV'] ,
        ['ppsh', 'PPSH00NOR'] ,
        ['prat', 'PRAT00ITA'] ,
        ['prij', 'PRIJ00SRB'] ,
        ['pryl', 'PRYL00UKR'] ,
        ['psto', 'PSTO00PRT'] ,
        ['pstv', 'PSTV00BLR'] ,
        ['ptal', 'PTAL00CAN'] ,
        ['ptrf', 'PTRF00CAN'] ,
        ['pulk', 'PULK00RUS'] ,
        ['puyv', 'PUYV00FRA'] ,
        ['pyha', 'PYHA00FIN'] ,
        ['pza2', 'PZA200SVN'] ,
        ['quad', 'QUAD00CAN'] ,
        ['rah1', 'RAH100UKR'] ,
        ['rant', 'RANT00DEU'] ,
        ['redz', 'REDZ00POL'] ,
        ['rio1', 'RIO100ESP'] ,
        ['rivo', 'RIVO00ITA'] ,
        ['rom2', 'ROM200FIN'] ,
        ['rove', 'ROVE00ITA'] ,
        ['rvne', 'RVNE00UKR'] ,
        ['saba', 'SABA00SRB'] ,
        ['sala', 'SALA00ESP'] ,
        ['sart', 'SART00ITA'] ,
        ['sas2', 'SAS200DEU'] ,
        ['savu', 'SAVU00FIN'] ,
        ['sbg2', 'SBG200AUT'] ,
        ['sc04', 'SC0400CAN'] ,
        ['scil', 'SCIL00GBR'] ,
        ['scoa', 'SCOA00FRA'] ,
        ['shoe', 'SHOE00GBR'] ,
        ['shpb', 'SHPB00CAN'] ,
        ['sid0', 'SID000SRB'] ,
        ['sjdv', 'SJDV00FRA'] ,
        ['ske0', 'SKE000SWE'] ,
        ['ske8', 'SKE800SWE'] ,
        ['smla', 'SMLA00UKR'] ,
        ['sneo', 'SNEO00GBR'] ,
        ['snik', 'SNIK00ITA'] ,
        ['soda', 'SODA00FIN'] ,
        ['sons', 'SONS00ESP'] ,
        ['spc1', 'SPC100BRA'] ,
        ['sprn', 'SPRN00HUN'] ,
        ['spt7', 'SPT700SWE'] ,
        ['srjv', 'SRJV00BIH'] ,
        ['stas', 'STAS00NOR'] ,
        ['stnb', 'STNB00PRT'] ,
        ['subo', 'SUBO00SRB'] ,
        ['sul5', 'SUL500DNK'] ,
        ['suld', 'SULD00DNK'] ,
        ['sun6', 'SUN600SWE'] ,
        ['sur4', 'SUR400EST'] ,
        ['sve6', 'SVE600SWE'] ,
        ['svll', 'SVLL00ITA'] ,
        ['swas', 'SWAS00GBR'] ,
        ['swki', 'SWKI00POL'] ,
        ['tahb', 'TAHB00CAN'] ,
        ['tar0', 'TAR000ESP'] ,
        ['teja', 'TEJA00CHL'] ,
        ['teos', 'TEOS00ITA'] ,
        ['ter2', 'TER200UKR'] ,
        ['terc', 'TERC00PRT'] ,
        ['ters', 'TERS00NLD'] ,
        ['teru', 'TERU00ESP'] ,
        ['tll1', 'TLL100IRL'] ,
        ['tlmf', 'TLMF00FRA'] ,
        ['tn22', 'TN2200USA'] ,
        ['toil', 'TOIL00EST'] ,
        ['topp', 'TOPP00ITA'] ,
        ['tor1', 'TOR100ESP'] ,
        ['tor3', 'TOR300EST'] ,
        ['tori', 'TORI00ITA'] ,
        ['torn', 'TORN00FIN'] ,
        ['trds', 'TRDS00NOR'] ,
        ['treu', 'TREU00ITA'] ,
        ['trf2', 'TRF200AUT'] ,
        ['trmi', 'TRMI00ITA'] ,
        ['tsea', 'TSEA00USA'] ,
        ['tubo', 'TUBO00CZE'] ,
        ['tuc2', 'TUC200GRC'] ,
        ['tuo2', 'TUO200FIN'] ,
        ['txes', 'TXES00USA'] ,
        ['uben', 'UBEN00ITA'] ,
        ['ucag', 'UCAG00ITA'] ,
        ['ufcd', 'UFCD00BRA'] ,
        ['ume6', 'UME600SWE'] ,
        ['unpg', 'UNPG00ITA'] ,
        ['untr', 'UNTR00ITA'] ,
        ['usal', 'USAL00ITA'] ,
        ['usdl', 'USDL00POL'] ,
        ['vaa2', 'VAA200FIN'] ,
        ['vaas', 'VAAS00FIN'] ,
        ['vaco', 'VACO00CZE'] ,
        ['vae6', 'VAE600SWE'] ,
        ['vain', 'VAIN00LVA'] ,
        ['vala', 'VALA00ESP'] ,
        ['vale', 'VALE00ESP'] ,
        ['vars', 'VARS00NOR'] ,
        ['ven1', 'VEN100ITA'] ,
        ['vfch', 'VFCH00FRA'] ,
        ['vigi', 'VIGI00ITA'] ,
        ['vign', 'VIGN00ITA'] ,
        ['vigo', 'VIGO00ESP'] ,
        ['vil0', 'VIL000SWE'] ,
        ['vil6', 'VIL600SWE'] ,
        ['vir2', 'VIR200FIN'] ,
        ['virg', 'VIRG00ITA'] ,
        ['vis6', 'VIS600SWE'] ,
        ['vitr', 'VITR00BLR'] ,
        ['vlfr', 'VLFR00ITA'] ,
        ['vlis', 'VLIS00NLD'] ,
        ['vln1', 'VLN100IRL'] ,
        ['vlns', 'VLNS00LTU'] ,
        ['vnrs', 'VNRS00UKR'] ,
        ['vtrb', 'VTRB00ITA'] ,
        ['vtsp', 'VTSP00USA'] ,
        ['ware', 'WARE00BEL'] ,
        ['wosb', 'WOSB00CAN'] ,
        ['wrlg', 'WRLG00DEU'] ,
        ['wt21', 'WT2100DEU'] ,
        ['wtz2', 'WTZ200DEU'] ,
        ['wtzl', 'WTZL00DEU'] ,
        ['zada', 'ZADA00HRV'] ,
        ['zara', 'ZARA00ESP'] ,
        ['zouf', 'ZOUF00ITA'] ,
        ['zprs', 'ZPRS00UKR'] ,
        ['zywi', 'ZYWI00POL'] ,
        ['zzon', 'ZZON00HUN'] ,
        ['hkcl', 'HKCL00HKG'] ,
        ['hkfn', 'HKFN00HKG'] ,
        ['hkks', 'HKKS00HKG'] ,
        ['hkkt', 'HKKT00HKG'] ,
        ['hklm', 'HKLM00HKG'] ,
        ['hklt', 'HKLT00HKG'] ,
        ['hkmw', 'HKMW00HKG'] ,
        ['hknp', 'HKNP00HKG'] ,
        ['hkoh', 'HKOH00HKG'] ,
        ['hkpc', 'HKPC00HKG'] ,
        ['hkqt', 'HKQT00HKG'] ,
        ['hksc', 'HKSC00HKG'] ,
        ['hksl', 'HKSL00HKG'] ,
        ['hkss', 'HKSS00HKG'] ,
        ['hkst', 'HKST00HKG'] ,
        ['hktk', 'HKTK00HKG'] ,
        ['hkws', 'HKWS00HKG'] ,
        ['kyc1', 'KYC100HKG'] ,
        ['t430', 'T43000HKG'] ,
        ['2bdc', '2BDC00AUS'] ,
        ['2cow', '2COW00AUS'],
        ['2cuh', '2CUH00AUS'],
        ['2eck', '2ECK00AUS'],
        ['2fy2', '2FY200AUS'],
        ['2igb', '2IGB00AUS'],
        ['2lmr', '2LMR00AUS'],
        ['2or2', '2OR200AUS'],
        ['2rsm', '2RSM00AUS'],
        ['3bev', '3BEV00AUS'],
        ['3bll', '3BLL00AUS'],
        ['3da2', '3DA200AUS'],
        ['3da3', '3DA300AUS'],
        ['3grn', '3GRN00AUS'],
        ['3gtv', '3GTV00AUS'],
        ['3mse', '3MSE00AUS'],
        ['3pak', '3PAK00AUS'],
        ['3ter', '3TER00AUS'],
        ['3wkb', '3WKB00AUS'],
        ['3wnb', '3WNB00AUS'],
        ['3wrr', '3WRR00AUS'],
        ['4blv', '4BLV00AUS'],
        ['4cb2', '4CB200AUS'],
        ['4chr', '4CHR00AUS'],
        ['4gle', '4GLE00AUS'],
        ['4grm', '4GRM00AUS'],
        ['4gw2', '4GW200AUS'],
        ['4hax', '4HAX00AUS'],
        ['4ip3', '4IP300AUS'],
        ['4lce', '4LCE00AUS'],
        ['4mcy', '4MCY00AUS'],
        ['4mky', '4MKY00AUS'],
        ['4mrn', '4MRN00AUS'],
        ['4mtl', '4MTL00AUS'],
        ['4rma', '4RMA00AUS'],
        ['4spl', '4SPL00AUS'],
        ['4tam', '4TAM00AUS'],
        ['4wc2', '4WC200AUS'],
        ['4wit', '4WIT00AUS'],
        ['5boo', '5BOO00AUS'],
        ['5bwh', '5BWH00AUS'],
        ['5cal', '5CAL00AUS'],
        ['5clb', '5CLB00AUS'],
        ['5clv', '5CLV00AUS'],
        ['5cpr', '5CPR00AUS'],
        ['5dmp', '5DMP00AUS'],
        ['5frc', '5FRC00AUS'],
        ['5ga2', '5GA200AUS'],
        ['5gln', '5GLN00AUS'],
        ['5hpe', '5HPE00AUS'],
        ['5kmb', '5KMB00AUS'],
        ['5kth', '5KTH00AUS'],
        ['5lar', '5LAR00AUS'],
        ['5lch', '5LCH00AUS'],
        ['5lok', '5LOK00AUS'],
        ['5lyn', '5LYN00AUS'],
        ['5mam', '5MAM00AUS'],
        ['5man', '5MAN00AUS'],
        ['5mip', '5MIP00AUS'],
        ['5mpl', '5MPL00AUS'],
        ['5mtb', '5MTB00AUS'],
        ['5nar', '5NAR00AUS'],
        ['5pdy', '5PDY00AUS'],
        ['5pta', '5PTA00AUS'],
        ['5rbt', '5RBT00AUS'],
        ['5reg', '5REG00AUS'],
        ['5rmk', '5RMK00AUS'],
        ['5rvp', '5RVP00AUS'],
        ['5rvt', '5RVT00AUS'],
        ['5slk', '5SLK00AUS'],
        ['5str', '5STR00AUS'],
        ['5wlt', '5WLT00AUS'],
        ['5wng', '5WNG00AUS'],
        ['5wrb', '5WRB00AUS'],
        ['5yan', '5YAN00AUS'],
        ['7auf', '7AUF00AUS'],
        ['7cbr', '7CBR00AUS'],
        ['7cra', '7CRA00AUS'],
        ['7dln', '7DLN00AUS'],
        ['7exe', '7EXE00AUS'],
        ['7hbt', '7HBT00AUS'],
        ['7kng', '7KNG00AUS'],
        ['7la2', '7LA200AUS'],
        ['7sct', '7SCT00AUS'],
        ['7sis', '7SIS00AUS'],
        ['7sth', '7STH00AUS'],
        ['8bun', '8BUN00AUS'],
        ['8cl2', '8CL200AUS'],
        ['8cwp', '8CWP00AUS'],
        ['8frm', '8FRM00AUS'],
        ['8grd', '8GRD00AUS'],
        ['8kat', '8KAT00AUS'],
        ['8kln', '8KLN00AUS'],
        ['8kwn', '8KWN00AUS'],
        ['8man', '8MAN00AUS'],
        ['8mdn', '8MDN00AUS'],
        ['8min', '8MIN00AUS'],
        ['8mrr', '8MRR00AUS'],
        ['8rcf', '8RCF00AUS'],
        ['8whs', '8WHS00AUS'],
        ['abny', 'ABNY00AUS'],
        ['acl2', 'ACL200AUS'],
        ['adde', 'ADDE00AUS'],
        ['admn', 'ADMN00AUS'],
        ['albu', 'ALBU00AUS'],
        ['alby', 'ALBY00AUS'],
        ['alxa', 'ALXA00AUS'],
        ['anda', 'ANDA00AUS'],
        ['angs', 'ANGS00AUS'],
        ['anna', 'ANNA00AUS'],
        ['antw', 'ANTW00AUS'],
        ['apsl', 'APSL00AUS'],
        ['arcd', 'ARCD00AUS'],
        ['ard2', 'ARD200AUS'],
        ['ardl', 'ARDL00AUS'],
        ['armc', 'ARMC00AUS'],
        ['armd', 'ARMD00AUS'],
        ['arrt', 'ARRT00AUS'],
        ['arub', 'ARUB00AUS'],
        ['ashf', 'ASHF00AUS'],
        ['babn', 'BABN00AUS'],
        ['bala', 'BALA00AUS'],
        ['balc', 'BALC00AUS'],
        ['bali', 'BALI00AUS'],
        ['ball', 'BALL00AUS'],
        ['balm', 'BALM00AUS'],
        ['baln', 'BALN00AUS'],
        ['bamb', 'BAMB00AUS'],
        ['bank', 'BANK00AUS'],
        ['bath', 'BATH00AUS'],
        ['bbdh', 'BBDH00AUS'],
        ['bboo', 'BBOO00AUS'],
        ['bchp', 'BCHP00AUS'],
        ['bdle', 'BDLE00AUS'],
        ['bdmr', 'BDMR00AUS'],
        ['bdst', 'BDST00AUS'],
        ['bdvl', 'BDVL00AUS'],
        ['bee2', 'BEE200AUS'],
        ['beec', 'BEEC00AUS'],
        ['bega', 'BEGA00AUS'],
        ['begs', 'BEGS00AUS'],
        ['beri', 'BERI00AUS'],
        ['berm', 'BERM00AUS'],
        ['beua', 'BEUA00AUS'],
        ['bht2', 'BHT200AUS'],
        ['bich', 'BICH00AUS'],
        ['bind', 'BIND00AUS'],
        ['bing', 'BING00AUS'],
        ['binn', 'BINN00AUS'],
        ['bjct', 'BJCT00AUS'],
        ['bknl', 'BKNL00AUS'],
        ['blck', 'BLCK00AUS'],
        ['blgl', 'BLGL00AUS'],
        ['blkt', 'BLKT00AUS'],
        ['blmt', 'BLMT00AUS'],
        ['blrn', 'BLRN00AUS'],
        ['bluf', 'BLUF00NZL'],
        ['bman', 'BMAN00AUS'],
        ['bmsh', 'BMSH00AUS'],
        ['bnby', 'BNBY00AUS'],
        ['bndc', 'BNDC00AUS'],
        ['bndr', 'BNDR00AUS'],
        ['bndy', 'BNDY00AUS'],
        ['bnie', 'BNIE00AUS'],
        ['bnla', 'BNLA00AUS'],
        ['boig', 'BOIG00AUS'],
        ['bolc', 'BOLC00AUS'],
        ['bomb', 'BOMB00AUS'],
        ['bone', 'BONE00AUS'],
        ['bool', 'BOOL00AUS'],
        ['boor', 'BOOR00AUS'],
        ['bora', 'BORA00AUS'],
        ['bort', 'BORT00AUS'],
        ['both', 'BOTH00AUS'],
        ['boyd', 'BOYD00AUS'],
        ['brba', 'BRBA00AUS'],
        ['brdw', 'BRDW00AUS'],
        ['brin', 'BRIN00AUS'],
        ['brla', 'BRLA00AUS'],
        ['brnd', 'BRND00AUS'],
        ['bro1', 'BRO100AUS'],
        ['broc', 'BROC00AUS'],
        ['brui', 'BRUI00AUS'],
        ['brwn', 'BRWN00AUS'],
        ['btyp', 'BTYP00AUS'],
        ['buch', 'BUCH00AUS'],
        ['bula', 'BULA00AUS'],
        ['bund', 'BUND00AUS'],
        ['bur2', 'BUR200AUS'],
        ['bura', 'BURA00AUS'],
        ['burk', 'BURK00AUS'],
        ['buss', 'BUSS00AUS'],
        ['ca07', 'CA0700AUS'],
        ['ca10', 'CA1000AUS'],
        ['camb', 'CAMB00IDN'],
        ['canr', 'CANR00AUS'],
        ['carg', 'CARG00AUS'],
        ['cbar', 'CBAR00AUS'],
        ['cbel', 'CBEL00AUS'],
        ['cbg2', 'CBG200AUS'],
        ['cbla', 'CBLA00AUS'],
        ['cble', 'CBLE00AUS'],
        ['cblt', 'CBLT00AUS'],
        ['cbra', 'CBRA00AUS'],
        ['ccpl', 'CCPL00AUS'],
        ['cdwl', 'CDWL00AUS'],
        ['cess', 'CESS00AUS'],
        ['chcc', 'CHCC00AUS'],
        ['chge', 'CHGE00AUS'],
        ['chid', 'CHID00AUS'],
        ['chnn', 'CHNN00JPN'],
        ['chsm', 'CHSM00AUS'],
        ['cktn', 'CKTN00AUS'],
        ['ckwl', 'CKWL00AUS'],
        ['clac', 'CLAC00AUS'],
        ['clah', 'CLAH00AUS'],
        ['clbi', 'CLBI00AUS'],
        ['clbn', 'CLBN00AUS'],
        ['clev', 'CLEV00AUS'],
        ['clon', 'CLON00AUS'],
        ['clum', 'CLUM00AUS'],
        ['clve', 'CLVE00AUS'],
        ['clyt', 'CLYT00AUS'],
        ['cmak', 'CMAK00IDN'],
        ['cnbn', 'CNBN00AUS'],
        ['cnda', 'CNDA00AUS'],
        ['cndo', 'CNDO00AUS'],
        ['cnvl', 'CNVL00AUS'],
        ['cnvn', 'CNVN00AUS'],
        ['cnwd', 'CNWD00AUS'],
        ['coal', 'COAL00CHN'],
        ['cobh', 'COBH00AUS'],
        ['coen', 'COEN00AUS'],
        ['coff', 'COFF00AUS'],
        ['cole', 'COLE00AUS'],
        ['coll', 'COLL00AUS'],
        ['coma', 'COMA00AUS'],
        ['coob', 'COOB00AUS'],
        ['cool', 'COOL00AUS'],
        ['cops', 'COPS00AUS'],
        ['corm', 'CORM00NZL'],
        ['cory', 'CORY00AUS'],
        ['cota', 'COTA00AUS'],
        ['cpla', 'CPLA00AUS'],
        ['cpon', 'CPON00IDN'],
        ['cran', 'CRAN00AUS'],
        ['crdx', 'CRDX00AUS'],
        ['crkm', 'CRKM00AUS'],
        ['crns', 'CRNS00AUS'],
        ['croy', 'CROY00AUS'],
        ['crsy', 'CRSY00AUS'],
        ['csno', 'CSNO00AUS'],
        ['cstr', 'CSTR00AUS'],
        ['ctmd', 'CTMD00AUS'],
        ['ctwr', 'CTWR00AUS'],
        ['cudg', 'CUDG00AUS'],
        ['cuke', 'CUKE00IDN'],
        ['cund', 'CUND00AUS'],
        ['cwra', 'CWRA00AUS'],
        ['dalb', 'DALB00AUS'],
        ['dbbo', 'DBBO00AUS'],
        ['deag', 'DEAG00AUS'],
        ['delo', 'DELO00AUS'],
        ['devo', 'DEVO00AUS'],
        ['dfrd', 'DFRD00AUS'],
        ['ding', 'DING00AUS'],
        ['dixl', 'DIXL00AUS'],
        ['dlqn', 'DLQN00AUS'],
        ['dnvk', 'DNVK00NZL'],
        ['doda', 'DODA00AUS'],
        ['dorr', 'DORR00AUS'],
        ['dowe', 'DOWE00AUS'],
        ['dprt', 'DPRT00AUS'],
        ['drgo', 'DRGO00AUS'],
        ['duar', 'DUAR00AUS'],
        ['dune', 'DUNE00AUS'],
        ['dwel', 'DWEL00AUS'],
        ['dwhy', 'DWHY00AUS'],
        ['dwsn', 'DWSN00AUS'],
        ['ebnk', 'EBNK00AUS'],
        ['echu', 'ECHU00AUS'],
        ['ecor', 'ECOR00AUS'],
        ['eden', 'EDEN00AUS'],
        ['eds1', 'EDS100AUS'],
        ['edsv', 'EDSV00AUS'],
        ['eml2', 'EML200AUS'],
        ['emmd', 'EMMD00AUS'],
        ['epsm', 'EPSM00AUS'],
        ['ermg', 'ERMG00AUS'],
        ['esdl', 'ESDL00AUS'],
        ['espa', 'ESPA00AUS'],
        ['eung', 'EUNG00AUS'],
        ['eura', 'EURA00AUS'],
        ['ewan', 'EWAN00AUS'],
        ['exmt', 'EXMT00AUS'],
        ['fdrn', 'FDRN00AUS'],
        ['fghd', 'FGHD00AUS'],
        ['flgp', 'FLGP00AUS'],
        ['flnd', 'FLND00AUS'],
        ['fnts', 'FNTS00AUS'],
        ['fomo', 'FOMO00CHN'],
        ['fors', 'FORS00AUS'],
        ['frb2', 'FRB200AUS'],
        ['froy', 'FROY00AUS'],
        ['fstr', 'FSTR00AUS'],
        ['ftdn', 'FTDN00AUS'],
        ['gabo', 'GABO00AUS'],
        ['gatt', 'GATT00AUS'],
        ['gdam', 'GDAM00AUS'],
        ['gela', 'GELA00AUS'],
        ['geli', 'GELI00AUS'],
        ['gfel', 'GFEL00AUS'],
        ['gfth', 'GFTH00AUS'],
        ['gftn', 'GFTN00AUS'],
        ['gies', 'GIES00AUS'],
        ['gilg', 'GILG00AUS'],
        ['giru', 'GIRU00AUS'],
        ['gisb', 'GISB00NZL'],
        ['glb2', 'GLB200AUS'],
        ['glbn', 'GLBN00AUS'],
        ['gldb', 'GLDB00NZL'],
        ['gldn', 'GLDN00AUS'],
        ['glng', 'GLNG00AUS'],
        ['gngn', 'GNGN00AUS'],
        ['gnoa', 'GNOA00AUS'],
        ['gong', 'GONG00AUS'],
        ['gool', 'GOOL00AUS'],
        ['goro', 'GORO00AUS'],
        ['grot', 'GROT00AUS'],
        ['gsbn', 'GSBN00AUS'],
        ['gunn', 'GUNN00AUS'],
        ['gurl', 'GURL00AUS'],
        ['haas', 'HAAS00NZL'],
        ['hamo', 'HAMO00AUS'],
        ['hamt', 'HAMT00NZL'],
        ['hast', 'HAST00NZL'],
        ['hatt', 'HATT00AUS'],
        ['hay1', 'HAY100AUS'],
        ['hbg1', 'HBG100AUS'],
        ['hbg2', 'HBG200AUS'],
        ['hbrg', 'HBRG00AUS'],
        ['hern', 'HERN00AUS'],
        ['heth', 'HETH00AUS'],
        ['hikb', 'HIKB00NZL'],
        ['hil1', 'HIL100AUS'],
        ['hill', 'HILL00AUS'],
        ['hlb2', 'HLB200AUS'],
        ['hnis', 'HNIS00AUS'],
        ['hnsb', 'HNSB00AUS'],
        ['hoba', 'HOBA00AUS'],
        ['hoki', 'HOKI00NZL'],
        ['hoth', 'HOTH00AUS'],
        ['hrsm', 'HRSM00AUS'],
        ['hrvy', 'HRVY00AUS'],
        ['hugh', 'HUGH00AUS'],
        ['hvyb', 'HVYB00AUS'],
        ['hwod', 'HWOD00AUS'],
        ['hwsp', 'HWSP00AUS'],
        ['hydn', 'HYDN00AUS'],
        ['iama', 'IAMA00AUS'],
        ['igwd', 'IGWD00AUS'],
        ['ihoe', 'IHOE00AUS'],
        ['imka', 'IMKA00AUS'],
        ['ingh', 'INGH00AUS'],
        ['injn', 'INJN00AUS'],
        ['invl', 'INVL00AUS'],
        ['ips3', 'IPS300AUS'],
        ['irym', 'IRYM00AUS'],
        ['jab2', 'JAB200AUS'],
        ['jeri', 'JERI00AUS'],
        ['jerv', 'JERV00AUS'],
        ['jlck', 'JLCK00AUS'],
        ['joon', 'JOON00AUS'],
        ['jplm', 'JPLM00Sta'],
        ['kaik', 'KAIK00NZL'],
        ['kal5', 'KAL500AUS'],
        ['kalg', 'KALG00AUS'],
        ['karu', 'KARU00AUS'],
        ['kat2', 'KAT200AUS'],
        ['kawa', 'KAWA00AUS'],
        ['kdal', 'KDAL00AUS'],
        ['keln', 'KELN00AUS'],
        ['kepk', 'KEPK00AUS'],
        ['kgis', 'KGIS00AUS'],
        ['kilk', 'KILK00AUS'],
        ['kilm', 'KILM00AUS'],
        ['king', 'KING00AUS'],
        ['kirr', 'KIRR00AUS'],
        ['kist', 'KIST00AUS'],
        ['kjng', 'KJNG00AUS'],
        ['kman', 'KMAN00AUS'],
        ['kncb', 'KNCB00AUS'],
        ['knox', 'KNOX00AUS'],
        ['knwr', 'KNWR00AUS'],
        ['knya', 'KNYA00JPN'],
        ['koum', 'KOUM00AUS'],
        ['krng', 'KRNG00AUS'],
        ['ktdt', 'KTDT00JPN'],
        ['ktia', 'KTIA00NZL'],
        ['ktmb', 'KTMB00AUS'],
        ['kton', 'KTON00AUS'],
        ['ktwn', 'KTWN00AUS'],
        ['kubn', 'KUBN00AUS'],
        ['kulw', 'KULW00AUS'],
        ['kunu', 'KUNU00AUS'],
        ['kurj', 'KURJ00AUS'],
        ['laks', 'LAKS00AUS'],
        ['lalb', 'LALB00AUS'],
        ['lamb', 'LAMB00AUS'],
        ['lann', 'LANN00AUS'],
        ['larr', 'LARR00AUS'],
        ['laun', 'LAUN00AUS'],
        ['lcl2', 'LCL200AUS'],
        ['leth', 'LETH00AUS'],
        ['lexa', 'LEXA00NZL'],
        ['lgow', 'LGOW00AUS'],
        ['lgth', 'LGTH00AUS'],
        ['liaw', 'LIAW00AUS'],
        ['lily', 'LILY00AUS'],
        ['lipo', 'LIPO00AUS'],
        ['liri', 'LIRI00AUS'],
        ['lkht', 'LKHT00AUS'],
        ['lkta', 'LKTA00NZL'],
        ['lkya', 'LKYA00AUS'],
        ['lngr', 'LNGR00AUS'],
        ['loby', 'LOBY00AUS'],
        ['lona', 'LONA00AUS'],
        ['loon', 'LOON00AUS'],
        ['lord', 'LORD00AUS'],
        ['loth', 'LOTH00AUS'],
        ['lrne', 'LRNE00AUS'],
        ['lsmr', 'LSMR00AUS'],
        ['ltsp', 'LTSP00AUS'],
        ['lura', 'LURA00AUS'],
        ['mack', 'MACK00AUS'],
        ['maff', 'MAFF00AUS'],
        ['main', 'MAIN00AUS'],
        ['mamr', 'MAMR00AUS'],
        ['mamu', 'MAMU00AUS'],
        ['many', 'MANY00AUS'],
        ['mary', 'MARY00AUS'],
        ['mbch', 'MBCH00AUS'],
        ['mbll', 'MBLL00AUS'],
        ['mcnt', 'MCNT00AUS'],
        ['mdrh', 'MDRH00AUS'],
        ['mena', 'MENA00AUS'],
        ['meno', 'MENO00AUS'],
        ['meth', 'METH00NZL'],
        ['mgrv', 'MGRV00AUS'],
        ['mhop', 'MHOP00AUS'],
        ['mian', 'MIAN00AUS'],
        ['midg', 'MIDG00AUS'],
        ['midl', 'MIDL00AUS'],
        ['mimi', 'MIMI00AUS'],
        ['mirc', 'MIRC00AUS'],
        ['mitt', 'MITT00AUS'],
        ['mker', 'MKER00AUS'],
        ['mlak', 'MLAK00AUS'],
        ['mlap', 'MLAP00AUS'],
        ['mmar', 'MMAR00AUS'],
        ['mnd3', 'MND300AUS'],
        ['mnde', 'MNDE00AUS'],
        ['mngo', 'MNGO00AUS'],
        ['mnis', 'MNIS00AUS'],
        ['mnpk', 'MNPK00AUS'],
        ['mnsf', 'MNSF00AUS'],
        ['mnto', 'MNTO00AUS'],
        ['mnum', 'MNUM00AUS'],
        ['mogo', 'MOGO00AUS'],
        ['moly', 'MOLY00AUS'],
        ['moog', 'MOOG00AUS'],
        ['mool', 'MOOL00AUS'],
        ['moon', 'MOON00AUS'],
        ['moor', 'MOOR00AUS'],
        ['moss', 'MOSS00AUS'],
        ['moul', 'MOUL00AUS'],
        ['mrba', 'MRBA00AUS'],
        ['mree', 'MREE00AUS'],
        ['mrni', 'MRNI00AUS'],
        ['mrno', 'MRNO00AUS'],
        ['mrnt', 'MRNT00AUS'],
        ['mrnv', 'MRNV00AUS'],
        ['mrt1', 'MRT100AUS'],
        ['mrt2', 'MRT200AUS'],
        ['mrt4', 'MRT400AUS'],
        ['mrt5', 'MRT500AUS'],
        ['mrt6', 'MRT600AUS'],
        ['mrt7', 'MRT700AUS'],
        ['mrt8', 'MRT800AUS'],
        ['mrt9', 'MRT900AUS'],
        ['mrwa', 'MRWA00AUS'],
        ['mryb', 'MRYB00AUS'],
        ['msct', 'MSCT00AUS'],
        ['msv2', 'MSV200AUS'],
        ['mswl', 'MSWL00AUS'],
        ['mtbu', 'MTBU00AUS'],
        ['mtcv', 'MTCV00AUS'],
        ['mtdn', 'MTDN00AUS'],
        ['mtem', 'MTEM00AUS'],
        ['mtgb', 'MTGB00AUS'],
        ['mthr', 'MTHR00AUS'],
        ['mtis', 'MTIS00AUS'],
        ['mtjo', 'MTJO00NZL'],
        ['mtld', 'MTLD00AUS'],
        ['mtma', 'MTMA00AUS'],
        ['mudg', 'MUDG00AUS'],
        ['mulg', 'MULG00AUS'],
        ['mulm', 'MULM00AUS'],
        ['mung', 'MUNG00AUS'],
        ['murr', 'MURR00AUS'],
        ['mvil', 'MVIL00AUS'],
        ['mwal', 'MWAL00AUS'],
        ['myrt', 'MYRT00AUS'],
        ['mzsw', 'MZSW00JPN'],
        ['namb', 'NAMB00AUS'],
        ['namo', 'NAMO00AUS'],
        ['nbri', 'NBRI00AUS'],
        ['nbrk', 'NBRK00AUS'],
        ['nclf', 'NCLF00AUS'],
        ['ndra', 'NDRA00AUS'],
        ['nebo', 'NEBO00AUS'],
        ['nera', 'NERA00AUS'],
        ['newe', 'NEWE00AUS'],
        ['newh', 'NEWH00AUS'],
        ['ngan', 'NGAN00AUS'],
        ['nhav', 'NHAV00AUS'],
        ['nhil', 'NHIL00AUS'],
        ['nlnd', 'NLND00AUS'],
        ['nlsn', 'NLSN00NZL'],
        ['nlso', 'NLSO00AUS'],
        ['nmbn', 'NMBN00AUS'],
        ['nmtn', 'NMTN00AUS'],
        ['nooj', 'NOOJ00AUS'],
        ['noos', 'NOOS00AUS'],
        ['norf', 'NORF00AUS'],
        ['nors', 'NORS00AUS'],
        ['nosa', 'NOSA00AUS'],
        ['nowe', 'NOWE00AUS'],
        ['nply', 'NPLY00NZL'],
        ['nrmn', 'NRMN00AUS'],
        ['nrrg', 'NRRG00AUS'],
        ['nsta', 'NSTA00AUS'],
        ['ntjn', 'NTJN00AUS'],
        ['nula', 'NULA00AUS'],
        ['nwcs', 'NWCS00AUS'],
        ['nwra', 'NWRA00AUS'],
        ['nybg', 'NYBG00AUS'],
        ['nyma', 'NYMA00AUS'],
        ['oakv', 'OAKV00AUS'],
        ['obrn', 'OBRN00AUS'],
        ['omeo', 'OMEO00AUS'],
        ['onkp', 'ONKP00AUS'],
        ['orbo', 'ORBO00AUS'],
        ['orng', 'ORNG00AUS'],
        ['oxly', 'OXLY00AUS'],
        ['pach', 'PACH00AUS'],
        ['pbot', 'PBOT00AUS'],
        ['pctn', 'PCTN00AUS'],
        ['peri', 'PERI00AUS'],
        ['pian', 'PIAN00AUS'],
        ['pimp', 'PIMP00AUS'],
        ['piny', 'PINY00AUS'],
        ['pits', 'PITS00AUS'],
        ['pkhm', 'PKHM00AUS'],
        ['pknh', 'PKNH00AUS'],
        ['pkvl', 'PKVL00AUS'],
        ['plea', 'PLEA00AUS'],
        ['plsa', 'PLSA00AUS'],
        ['pmac', 'PMAC00AUS'],
        ['pmcv', 'PMCV00AUS'],
        ['pnla', 'PNLA00AUS'],
        ['pntl', 'PNTL00AUS'],
        ['poar', 'POAR00AUS'],
        ['poca', 'POCA00AUS'],
        ['poon', 'POON00AUS'],
        ['prce', 'PRCE00AUS'],
        ['prks', 'PRKS00AUS'],
        ['prot', 'PROT00AUS'],
        ['prtf', 'PRTF00AUS'],
        ['pthl', 'PTHL00AUS'],
        ['ptkl', 'PTKL00AUS'],
        ['ptld', 'PTLD00AUS'],
        ['ptlm', 'PTLM00AUS'],
        ['ptsv', 'PTSV00AUS'],
        ['puty', 'PUTY00AUS'],
        ['qclf', 'QCLF00AUS'],
        ['quam', 'QUAM00AUS'],
        ['quee', 'QUEE00AUS'],
        ['rami', 'RAMI00AUS'],
        ['rand', 'RAND00AUS'],
        ['rane', 'RANE00AUS'],
        ['rank', 'RANK00AUS'],
        ['rath', 'RATH00AUS'],
        ['ravn', 'RAVN00AUS'],
        ['raws', 'RAWS00AUS'],
        ['raym', 'RAYM00AUS'],
        ['rbvl', 'RBVL00AUS'],
        ['rbyl', 'RBYL00AUS'],
        ['rdg3', 'RDG300AUS'],
        ['rgln', 'RGLN00AUS'],
        ['rhpt', 'RHPT00AUS'],
        ['rivn', 'RIVN00AUS'],
        ['rkld', 'RKLD00AUS'],
        ['rnbo', 'RNBO00AUS'],
        ['rnsp', 'RNSP00AUS'],
        ['robi', 'ROBI00AUS'],
        ['roon', 'ROON00AUS'],
        ['rott', 'ROTT00AUS'],
        ['rsby', 'RSBY00AUS'],
        ['rsed', 'RSED00AUS'],
        ['rswt', 'RSWT00AUS'],
        ['ruth', 'RUTH00AUS'],
        ['ruus', 'RUUS00AUS'],
        ['rvso', 'RVSO00AUS'],
        ['rxby', 'RXBY00AUS'],
        ['ryls', 'RYLS00AUS'],
        ['sa45', 'SA4500AUS'],
        ['salt', 'SALT00AUS'],
        ['scdl', 'SCDL00AUS'],
        ['scon', 'SCON00AUS'],
        ['seal', 'SEAL00AUS'],
        ['sfld', 'SFLD00AUS'],
        ['skip', 'SKIP00AUS'],
        ['slad', 'SLAD00AUS'],
        ['sltc', 'SLTC00AUS'],
        ['sngo', 'SNGO00AUS'],
        ['spby', 'SPBY00AUS'],
        ['sppt', 'SPPT00AUS'],
        ['spwd', 'SPWD00AUS'],
        ['srip', 'SRIP00AUS'],
        ['srvc', 'SRVC00AUS'],
        ['stad', 'STAD00AUS'],
        ['stbn', 'STBN00AUS'],
        ['sthe', 'STHE00AUS'],
        ['sthg', 'STHG00AUS'],
        ['stlw', 'STLW00AUS'],
        ['stny', 'STNY00AUS'],
        ['str3', 'STR300AUS'],
        ['str9', 'STR900AUS'],
        ['strh', 'STRH00AUS'],
        ['surt', 'SURT00AUS'],
        ['swnh', 'SWNH00AUS'],
        ['swtc', 'SWTC00AUS'],
        ['sym1', 'SYM100AUS'],
        ['symr', 'SYMR00AUS'],
        ['tamw', 'TAMW00AUS'],
        ['taso', 'TASO00AUS'],
        ['tatu', 'TATU00AUS'],
        ['taup', 'TAUP00NZL'],
        ['tbob', 'TBOB00AUS'],
        ['tcby', 'TCBY00AUS'],
        ['telo', 'TELO00AUS'],
        ['terg', 'TERG00AUS'],
        ['thev', 'THEV00AUS'],
        ['thka', 'THKA00JPN'],
        ['tibd', 'TIBD00AUS'],
        ['tkbg', 'TKBG00JPN'],
        ['tlpa', 'TLPA00AUS'],
        ['tltn', 'TLTN00AUS'],
        ['tlwd', 'TLWD00AUS'],
        ['tmba', 'TMBA00AUS'],
        ['tmbo', 'TMBO00AUS'],
        ['tmra', 'TMRA00AUS'],
        ['tmut', 'TMUT00AUS'],
        ['tngl', 'TNGL00AUS'],
        ['tntr', 'TNTR00AUS'],
        ['tomp', 'TOMP00AUS'],
        ['toog', 'TOOG00AUS'],
        ['tork', 'TORK00AUS'],
        ['tott', 'TOTT00AUS'],
        ['trar', 'TRAR00AUS'],
        ['trn1', 'TRN100AUS'],
        ['trng', 'TRNG00NZL'],
        ['trug', 'TRUG00AUS'],
        ['tsmi', 'TSMI00AUS'],
        ['tsrv', 'TSRV00AUS'],
        ['tull', 'TULL00AUS'],
        ['tuly', 'TULY00AUS'],
        ['turo', 'TURO00AUS'],
        ['ucla', 'UCLA00AUS'],
        ['ugar', 'UGAR00AUS'],
        ['ulla', 'ULLA00AUS'],
        ['unde', 'UNDE00AUS'],
        ['unw2', 'UNW200AUS'],
        ['vcth', 'VCTH00AUS'],
        ['vgmt', 'VGMT00NZL'],
        ['vhb3', 'VHB300AUS'],
        ['vlwd', 'VLWD00AUS'],
        ['wag1', 'WAG100AUS'],
        ['wagn', 'WAGN00AUS'],
        ['waik', 'WAIK00AUS'],
        ['wakl', 'WAKL00AUS'],
        ['walh', 'WALH00AUS'],
        ['walw', 'WALW00AUS'],
        ['wang', 'WANG00NZL'],
        ['waoo', 'WAOO00AUS'],
        ['wara', 'WARA00AUS'],
        ['wari', 'WARI00AUS'],
        ['warw', 'WARW00AUS'],
        ['wbol', 'WBOL00AUS'],
        ['wchp', 'WCHP00AUS'],
        ['wdbg', 'WDBG00AUS'],
        ['wdng', 'WDNG00AUS'],
        ['wedd', 'WEDD00AUS'],
        ['weem', 'WEEM00AUS'],
        ['weia', 'WEIA00AUS'],
        ['wend', 'WEND00AUS'],
        ['went', 'WENT00AUS'],
        ['west', 'WEST00NZL'],
        ['wfal', 'WFAL00AUS'],
        ['wgba', 'WGBA00AUS'],
        ['wgga', 'WGGA00AUS'],
        ['wgtt', 'WGTT00NZL'],
        ['whkt', 'WHKT00NZL'],
        ['whla', 'WHLA00AUS'],
        ['whng', 'WHNG00NZL'],
        ['wilu', 'WILU00AUS'],
        ['wlal', 'WLAL00AUS'],
        ['wlca', 'WLCA00AUS'],
        ['wlgt', 'WLGT00AUS'],
        ['wlmd', 'WLMD00AUS'],
        ['wltn', 'WLTN00AUS'],
        ['wlwn', 'WLWN00AUS'],
        ['wmga', 'WMGA00AUS'],
        ['wnbl', 'WNBL00AUS'],
        ['wndn', 'WNDN00AUS'],
        ['wnga', 'WNGA00AUS'],
        ['wntn', 'WNTN00AUS'],
        ['wolp', 'WOLP00AUS'],
        ['wong', 'WONG00AUS'],
        ['wori', 'WORI00AUS'],
        ['wotg', 'WOTG00AUS'],
        ['wpnd', 'WPND00AUS'],
        ['wrbe', 'WRBE00AUS'],
        ['wrdi', 'WRDI00AUS'],
        ['wrpa', 'WRPA00NZL'],
        ['wrrn', 'WRRN00AUS'],
        ['wsea', 'WSEA00AUS'],
        ['wtcf', 'WTCF00AUS'],
        ['wthl', 'WTHL00AUS'],
        ['wton', 'WTON00AUS'],
        ['wwlg', 'WWLG00AUS'],
        ['wych', 'WYCH00AUS'],
        ['wyng', 'WYNG00AUS'],
        ['wyrl', 'WYRL00AUS'],
        ['yall', 'YALL00AUS'],
        ['yaro', 'YARO00AUS'],
        ['yars', 'YARS00AUS'],
        ['yass', 'YASS00AUS'],
        ['yeel', 'YEEL00AUS'],
        ['yelo', 'YELO00AUS'],
        ['yiel', 'YIEL00AUS'],
        ['ylrb', 'YLRB00AUS'],
        ['ymba', 'YMBA00AUS'],
        ['ynki', 'YNKI00AUS'],
        ['yrm2', 'YRM200AUS'],
        ['yula', 'YULA00AUS'],
        ['yung', 'YUNG00AUS'],
        ['yunt', 'YUNT00AUS']
        ]


for site in supplementSite:
    mgex.append(site)